### ISSUE TITLE
[PATCH] btrfs: reject unknown mount options correctly

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#1002]
Link to patches

https://lore.kernel.org/linux-btrfs/a6a954a1f1c7d612104279c62916f49e47ba5811.1697085884.git.wqu@suse.com/

b4 am a6a954a1f1c7d612104279c62916f49e47ba5811.1697085884.git.wqu@suse.com

**Comment by kdave** [comment]
Will be superseded by the new mount API conversion.
