### ISSUE TITLE
[PATCH] btrfs-progs: restore: Have -l display subvolume name

### ISSUE THREAD

**Issue by danobi** [btrfs/linux#102]
Link to patches

https://lore.kernel.org/linux-btrfs/547cf7d97e32b542f4a552c7319b167dd6b94403.1603758365.git.dxu@dxuuu.xyz/

b4 am 547cf7d97e32b542f4a552c7319b167dd6b94403.1603758365.git.dxu@dxuuu.xyz

**Comment by kdave** [comment]
This is a progs patch, please don't open issue in this repo.

**Comment by danobi** [comment]
Ah sorry, will remember.
