### ISSUE TITLE
[PATCH] btrfs: get rid of memparse() for sysfs operations

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#1047]
Link to patches

https://lore.kernel.org/linux-btrfs/69524a828a08d8d88face116ea7563fd34275815.1701920169.git.wqu@suse.com/

b4 am 69524a828a08d8d88face116ea7563fd34275815.1701920169.git.wqu@suse.com

**Comment by kdave** [comment]
We'll keep the memparse.
