### ISSUE TITLE
[PATCH] btrfs: prefer to allocate larger folio for metadata

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#1051]
Link to patches

https://lore.kernel.org/linux-btrfs/4b8c4ec119e2f24fdeafc29d8e654b5fded39eb2.1702360704.git.wqu@suse.com/

b4 am 4b8c4ec119e2f24fdeafc29d8e654b5fded39eb2.1702360704.git.wqu@suse.com

**Comment by kdave** [comment]
Superseded by #1068
