### ISSUE TITLE
[PATCH] btrfs: don't double put our subpage reference in

### ISSUE THREAD

**Issue by josefbacik** [btrfs/linux#1054]
Link to patches

https://lore.kernel.org/linux-btrfs/dd32747467e46ee7ce4feb8a1c3a30d93fd4b133.1702593420.git.josef@toxicpanda.com/

b4 am dd32747467e46ee7ce4feb8a1c3a30d93fd4b133.1702593420.git.josef@toxicpanda.com

**Comment by kdave** [comment]
Folded.
