### ISSUE TITLE
[PATCH] btrfs: handle existing eb in the radix tree properly

### ISSUE THREAD

**Issue by josefbacik** [btrfs/linux#1058]
Link to patches

https://lore.kernel.org/linux-btrfs/93ba6929e6ce070bd27bd80220bff7112793a3ca.1702658189.git.josef@toxicpanda.com/

b4 am 93ba6929e6ce070bd27bd80220bff7112793a3ca.1702658189.git.josef@toxicpanda.com

**Comment by kdave** [comment]
Folded.
