### ISSUE TITLE
[PATCH v2] btrfs: prefer to allocate larger folio for metadata

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#1068]
Link to patches

https://lore.kernel.org/linux-btrfs/b2a33b0d75b29a0945b58342d021b24cf157114c.1704434178.git.wqu@suse.com/

b4 am b2a33b0d75b29a0945b58342d021b24cf157114c.1704434178.git.wqu@suse.com

**Comment by kdave** [comment]
Note from today's call, large folis are not reliable on other filesystems yet, we don't need to rush the switch.

**Comment by adam900710** [comment]
That's fine, although for this, it's only for metadata, unlike the other fses' plan for all data/metadata.

So I'd say it may still be worth a try.

**Comment by kdave** [comment]
I have the patch in misc-next and that gets testing in linux-next. The folio conversions have been unblocked and we should finish that before switching to large folios, so I'm tagging that as for 6.11.

**Comment by kdave** [comment]
Big folios don't work yet and no point testing it as it can crash in page migration or elsewhere. Patch removed from misc-next, normal folio conversion will be done first.
