### ISSUE TITLE
[PATCH] btrfs: reject zoned RW mount if sectorsize is smaller than

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#1139]
Link to patches

https://lore.kernel.org/linux-btrfs/2a19a500ccb297397018dac23d30106977153d62.1707714970.git.wqu@suse.com/

b4 am 2a19a500ccb297397018dac23d30106977153d62.1707714970.git.wqu@suse.com

**Comment by kdave** [comment]
As said can be dropped.
