### ISSUE TITLE
[PATCH v2] btrfs: support device name lookup in forget

### ISSUE THREAD

**Issue by boryas** [btrfs/linux#1175]
Link to patches

https://lore.kernel.org/linux-btrfs/659b811232f9c647e8a2250f6d4acd6a12751b6c.1709231726.git.boris@bur.io/

b4 am 659b811232f9c647e8a2250f6d4acd6a12751b6c.1709231726.git.boris@bur.io

**Comment by boryas** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/40d13cb5a18a2fcb5e667ee0bc61f2b7a12c93e4.1709233065.git.boris@bur.io/

b4 am 40d13cb5a18a2fcb5e667ee0bc61f2b7a12c93e4.1709233065.git.boris@bur.io

**Comment by kdave** [comment]
May be still relevant but need an update.
