### ISSUE TITLE
[PATCH] btrfs: warn on wrong dev_t in fs_devices cache

### ISSUE THREAD

**Issue by boryas** [btrfs/linux#1176]
Link to patches

https://lore.kernel.org/linux-btrfs/c07bfcf1ca8ec66b8cfd1c6afae0b755af655cd1.1709251888.git.boris@bur.io/

b4 am c07bfcf1ca8ec66b8cfd1c6afae0b755af655cd1.1709251888.git.boris@bur.io

**Comment by kdave** [comment]
Fixed by "btrfs: validate device maj:min during open"
