### ISSUE TITLE
[PATCH] btrfs: wait on v1 cache for log replay

### ISSUE THREAD

**Issue by josefbacik** [btrfs/linux#118]
Link to patches

https://lore.kernel.org/linux-btrfs/01bacd1faab24648e9701e34318f7bfd6a1f098b.1604608527.git.josef@toxicpanda.com/

b4 am 01bacd1faab24648e9701e34318f7bfd6a1f098b.1604608527.git.josef@toxicpanda.com

**Comment by kdave** [comment]
Folded to the patch, thanks.
