### ISSUE TITLE
[PATCH] btrfs: fix memory leak in btrfs_read_folio

### ISSUE THREAD

**Issue by morbidrsa** [btrfs/linux#1182]
Link to patches

https://lore.kernel.org/linux-btrfs/fb513314c27317128426ab6e84bbb644603e65f5.1709628782.git.jth@kernel.org/

b4 am fb513314c27317128426ab6e84bbb644603e65f5.1709628782.git.jth@kernel.org

**Comment by kdave** [comment]
Folded.
