### ISSUE TITLE
[PATCH v2] btrfs: don't hold dev_replace rwsem over whole of

### ISSUE THREAD

**Issue by morbidrsa** [btrfs/linux#1249]
Link to patches

https://lore.kernel.org/linux-btrfs/2454cd4eb1694d37056e492af32b23743c63202b.1714663442.git.jth@kernel.org/

b4 am 2454cd4eb1694d37056e492af32b23743c63202b.1714663442.git.jth@kernel.org

**Comment by kdave** [comment]
The mail is not in the lore archives and I don't see it in my mailboxes either.

**Comment by morbidrsa** [comment]
because I'm stupid and only sent it to myself... 

Sending out now.

**Comment by morbidrsa** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/20240508114016.18119-1-jth@kernel.org/

b4 am [220240508114016.18119-1-jth@kernel.org](mailto:20240508114016.18119-1-jth@kernel.org)
