### ISSUE TITLE
[PATCH 0/2] btrfs: clean up btrfs_iget, btrfs_iget_path usage

### ISSUE THREAD

**Issue by loemraw** [btrfs/linux#1369]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1723580508.git.loemra.dev@gmail.com/

b4 am cover.1723580508.git.loemra.dev@gmail.com

**Comment by adam900710** [comment]
Close with v3 submitted.

Next time please using the "--issue <id>" option from `workflow/scripts/btrfs-send-patches` script, which will just update the existing issue with a newer patch, without creating a new issue.
