### ISSUE TITLE
[PATCH v2 0/2] btrfs: clean up btrfs_iget, btrfs_iget_path usage

### ISSUE THREAD

**Issue by loemraw** [btrfs/linux#1377]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1724184314.git.loemra.dev@gmail.com/

b4 am cover.1724184314.git.loemra.dev@gmail.com

**Comment by adam900710** [comment]
Close with v3 submitted:

https://github.com/btrfs/linux/issues/1380
