### ISSUE TITLE
[PATCH RFC] btrfs: introduce qgroup dirty extents threshold mechanism for snapshot drop and inode truncation

### ISSUE THREAD

**Issue by kdave** [btrfs/linux#140]
https://lore.kernel.org/linux-btrfs/20201119072828.70909-1-wqu@suse.com/

b4 am 20201119072828.70909-1-wqu@suse.com

**Comment by kdave** [comment]
cc @adam900710
An RFC patch without comments, it's been stale for more than a year, removing from the queue.

**Comment by adam900710** [comment]
That one is replaced by the user-configurable version titled "btrfs: qgroup: address the performance penalty for subvolume dropping"

https://lore.kernel.org/linux-btrfs/20211207011655.21579-1-wqu@suse.com/
