### ISSUE TITLE
[PATCH v5] btrfs: try to search for data csums in commit root

### ISSUE THREAD

**Issue by boryas** [btrfs/linux#1429]
Link to patches

https://lore.kernel.org/linux-btrfs/9d12c373a49184e84897ff2d6df601f2c7c66a32.1728084164.git.boris@bur.io/

b4 am 9d12c373a49184e84897ff2d6df601f2c7c66a32.1728084164.git.boris@bur.io

**Comment by boryas** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/0a59693a70f542120a0302e9864e7f9b86e1cb4c.1728415983.git.boris@bur.io/

b4 am 0a59693a70f542120a0302e9864e7f9b86e1cb4c.1728415983.git.boris@bur.io

**Comment by boryas** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/01721e6680b4a05c06cea8afc98b1726102ba5f5.1728947030.git.boris@bur.io/

b4 am 01721e6680b4a05c06cea8afc98b1726102ba5f5.1728947030.git.boris@bur.io

**Comment by boryas** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/00aada8468cfc74d696dd98f9b8c603271905029.1729107891.git.boris@bur.io/

b4 am 00aada8468cfc74d696dd98f9b8c603271905029.1729107891.git.boris@bur.io

**Comment by boryas** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/8e334e4412410a46d3928950c796c9914cebdf92.1729537203.git.boris@bur.io/

b4 am 8e334e4412410a46d3928950c796c9914cebdf92.1729537203.git.boris@bur.io

**Comment by kdave** [comment]
Causes hangs, needs to be reworked.
