### ISSUE TITLE
Whom to contact regarding requests/changes for docs.kernel.org?

### ISSUE THREAD

**Issue by pjotrek-b** [btrfs/linux#1455]
Hello everyone :smile:

It's about btrfs-documentation:
I'd like to ask about technical details on extended attributes (xattrs) on btrfs, and found this page:
https://docs.kernel.org/6.1/filesystems/btrfs.html

Also:
https://btrfs.readthedocs.io/en/latest/

However, I couldn't find whom to engage with (contact email?) to discuss on btrfs' capabilities of using xattrs as a catalog-database.

Thanks for any information or links.

**Comment by kdave** [comment]
docs.kernel.org is generated from files in linux kernel git Documentation, the RTD docs are from btrfs-progs.git. Please open issues on github.com/kdave/btrfs-progs for documentation questions, suggestions or contributions.

**Comment by pjotrek-b** [comment]
Thank you! Will do.
