### ISSUE TITLE
[PATCH] btrfs: don't get an EINTR during drop_snapshot for reloc

### ISSUE THREAD

**Issue by josefbacik** [btrfs/linux#165]
Link to patches

https://lore.kernel.org/linux-btrfs/a72092d8058f1224efbc16be4d406dc7fcc60976.1608058461.git.josef@toxicpanda.com/

b4 am a72092d8058f1224efbc16be4d406dc7fcc60976.1608058461.git.josef@toxicpanda.com

**Comment by kdave** [comment]
Superseded by #167
