### ISSUE TITLE
[PATCH v15 00/42] btrfs: zoned block device support

### ISSUE THREAD

**Issue by morbidrsa** [btrfs/linux#179]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1608515994.git.naohiro.aota@wdc.com/

b4 am cover.1608515994.git.naohiro.aota@wdc.com

**Comment by naota** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1610693036.git.naohiro.aota@wdc.com/

b4 am cover.1610693036.git.naohiro.aota@wdc.com

**Comment by naota** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1611295439.git.naohiro.aota@wdc.com/

b4 am cover.1611295439.git.naohiro.aota@wdc.com

**Comment by naota** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1611627788.git.naohiro.aota@wdc.com/

b4 am cover.1611627788.git.naohiro.aota@wdc.com

**Comment by morbidrsa** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1612433345.git.naohiro.aota@wdc.com/

b4 am cover.1612433345.git.naohiro.aota@wdc.com
