### ISSUE TITLE
[PATCH] btrfs-progs: remove workaround for setting capabilities in

### ISSUE THREAD

**Issue by fdmanana** [btrfs/linux#193]
Link to patches

https://lore.kernel.org/linux-btrfs/e35e5d556cd5964a4ab80bdd997856ee5be8b888.1612870936.git.fdmanana@suse.com/

b4 am e35e5d556cd5964a4ab80bdd997856ee5be8b888.1612870936.git.fdmanana@suse.com

**Comment by kdave** [comment]
Progs patches are not tracked in this project.
