### ISSUE TITLE
[PATCH v2] btrfs: change handle_fs_error in recover_log_trees to

### ISSUE THREAD

**Issue by josefbacik** [btrfs/linux#249]
Link to patches

https://lore.kernel.org/linux-btrfs/e106a478e2d238b7315a19f62fabeae8e9bbb51f.1621265669.git.josef@toxicpanda.com/

b4 am e106a478e2d238b7315a19f62fabeae8e9bbb51f.1621265669.git.josef@toxicpanda.com

**Comment by josefbacik** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/0bc5200e1d20ddcad6d5a858cf00272197b3df67.1621521913.git.josef@toxicpanda.com/

b4 am 0bc5200e1d20ddcad6d5a858cf00272197b3df67.1621521913.git.josef@toxicpanda.com

**Comment by kdave** [comment]
Superseded by "btrfs: change handle_fs_error in recover_log_trees to aborts" from #259

**Comment by josefbacik** [comment]
This is superseded by #259
