### ISSUE TITLE
[PATCH] btrfs: abort the transaction if we fail to replay log trees

### ISSUE THREAD

**Issue by josefbacik** [btrfs/linux#255]
Link to patches

https://lore.kernel.org/linux-btrfs/9513d31a4d2559253088756f99d162abaf090ebd.1621438132.git.josef@toxicpanda.com/

b4 am 9513d31a4d2559253088756f99d162abaf090ebd.1621438132.git.josef@toxicpanda.com

**Comment by kdave** [comment]
Superseded by "btrfs: change handle_fs_error in recover_log_trees to aborts" from #259
