### ISSUE TITLE
[PATCH 10/12] btrfs: change our extent buffer lock to a rw_semaphore

### ISSUE THREAD

**Issue by kdave** [btrfs/linux#27]
https://lore.kernel.org/linux-btrfs/a34e67a2b1804ff57e488e685fcfe32acea7daed.1597938191.git.josef@toxicpanda.com

**Comment by josefbacik** [comment]
This is a test

**Comment by josefbacik** [comment]
a  c d

**Comment by josefbacik** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/12345/

b4 am 12345

**Comment by josefbacik** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/12345/

b4 am 12345
