### ISSUE TITLE
[PATCH] btrfs: fix deadlock with concurrent chunk allocations

### ISSUE THREAD

**Issue by fdmanana** [btrfs/linux#275]
Link to patches

https://lore.kernel.org/linux-btrfs/b8b7b585ec8b7b2924fd5995951a0d16d2e394d7.1624369954.git.fdmanana@suse.com/

b4 am b8b7b585ec8b7b2924fd5995951a0d16d2e394d7.1624369954.git.fdmanana@suse.com

**Comment by kdave** [comment]
Superseded by #280
