### ISSUE TITLE
[PATCH v3] btrfs: zoned: revert "btrfs: zoned: fail mount if the

### ISSUE THREAD

**Issue by morbidrsa** [btrfs/linux#281]
Link to patches

https://lore.kernel.org/linux-btrfs/00c2351fa6070a149866df5e599e09c908e9cf26.1625127204.git.johannes.thumshirn@wdc.com/

b4 am 00c2351fa6070a149866df5e599e09c908e9cf26.1625127204.git.johannes.thumshirn@wdc.com

**Comment by morbidrsa** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/a6b7c5c38267fb410a4a4f711e986c863790ddf8.1625221720.git.johannes.thumshirn@wdc.com/

b4 am a6b7c5c38267fb410a4a4f711e986c863790ddf8.1625221720.git.johannes.thumshirn@wdc.com

**Comment by morbidrsa** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/2069666c4c5f68fafe0cfefdbc880fa6b4969217.1625225912.git.johannes.thumshirn@wdc.com/

b4 am 2069666c4c5f68fafe0cfefdbc880fa6b4969217.1625225912.git.johannes.thumshirn@wdc.com

**Comment by kdave** [comment]
Superseded by #277
