### ISSUE TITLE
[PATCH] btrfs: drop ret in ioctl_quota_rescan_status

### ISSUE THREAD

**Issue by asj** [btrfs/linux#297]
Link to patches

https://lore.kernel.org/linux-btrfs/c37927ff2082701c940d0aaad2301e4774159d74.1627452869.git.anand.jain@oracle.com/

b4 am c37927ff2082701c940d0aaad2301e4774159d74.1627452869.git.anand.jain@oracle.com

**Comment by kdave** [comment]
Merged long time ago as 991a3daeda983aa8, closing.
