### ISSUE TITLE
[PATCH RFC] btrfs: sysfs: bytes_zone_unusable is not under

### ISSUE THREAD

**Issue by asj** [btrfs/linux#303]
Link to patches

https://lore.kernel.org/linux-btrfs/8585061cc6672a4f3b985b7c387c7a8040af2a73.1628125287.git.anand.jain@oracle.com/

b4 am 8585061cc6672a4f3b985b7c387c7a8040af2a73.1628125287.git.anand.jain@oracle.com

**Comment by kdave** [comment]
Not needed.
