### ISSUE TITLE
[PATCH] btrfs: zoned: exclude relocation and page writeback

### ISSUE THREAD

**Issue by morbidrsa** [btrfs/linux#306]
Link to patches

https://lore.kernel.org/linux-btrfs/a858fb2ff980db27b3638e92f7d2d7a416b8e81e.1628776260.git.johannes.thumshirn@wdc.com/

b4 am a858fb2ff980db27b3638e92f7d2d7a416b8e81e.1628776260.git.johannes.thumshirn@wdc.com

**Comment by kdave** [comment]
Will be reworked.
