### ISSUE TITLE
[PATCH v3] btrfs: allow single disk devices to mount with older

### ISSUE THREAD

**Issue by josefbacik** [btrfs/linux#31]
Link to patches

https://lore.kernel.org/linux-btrfs/6b1f037344cd8d24566f3d9873b820a73384242c.1598995167.git.josef@toxicpanda.com/

b4 am 6b1f037344cd8d24566f3d9873b820a73384242c.1598995167.git.josef@toxicpanda.com

**Comment by josefbacik** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/990fe8a8efc2de74492a57148cdffe5dc9c02136.1610747845.git.josef@toxicpanda.com/

b4 am 990fe8a8efc2de74492a57148cdffe5dc9c02136.1610747845.git.josef@toxicpanda.com

**Comment by josefbacik** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/75f38ba99fde2f94066fb4578914241c0e2a8f9d.1636408300.git.josef@toxicpanda.com/

b4 am 75f38ba99fde2f94066fb4578914241c0e2a8f9d.1636408300.git.josef@toxicpanda.com

**Comment by josefbacik** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/1bf56a77b8b57cc3b993fda00752e79830685ffc.1674772170.git.josef@toxicpanda.com/

b4 am 1bf56a77b8b57cc3b993fda00752e79830685ffc.1674772170.git.josef@toxicpanda.com

**Comment by kdave** [comment]
Superseded by #707.
