### ISSUE TITLE
[PATCH v2 0/2] btrfs: re-define btrfs_raid_types

### ISSUE THREAD

**Issue by kdave** [btrfs/linux#354]
https://lore.kernel.org/linux-btrfs/20211027052859.44507-1-wqu@suse.com/

b4 am 20211027052859.44507-1-wqu@suse.com

**Comment by kdave** [comment]
cc @adam900710
The patchset is almost finished, only some macro naming changes. I'll mark it as stale and remove the issue after next release unless there's an update.

**Comment by kdave** [comment]
No update.

**Comment by adam900710** [comment]
Sorry, didn't notice until you closed the case.

Now I opened a new issue for it:
https://github.com/btrfs/linux/issues/482
