### ISSUE TITLE
[PATCH] btrfs: free device if we fail to open it

### ISSUE THREAD

**Issue by josefbacik** [btrfs/linux#368]
Link to patches

https://lore.kernel.org/linux-btrfs/7cfd63a1232900565abf487e82b7aa4af5fbca29.1638393521.git.josef@toxicpanda.com/

b4 am 7cfd63a1232900565abf487e82b7aa4af5fbca29.1638393521.git.josef@toxicpanda.com

**Comment by kdave** [comment]
As was discussed under the patch a different fix will be done.
