### ISSUE TITLE
[PATCH] btrfs: zoned: fix leak of zone_info in

### ISSUE THREAD

**Issue by morbidrsa** [btrfs/linux#376]
Link to patches

https://lore.kernel.org/linux-btrfs/8a54e85cf93d2042f1a2e29517f8f91fce56f6ab.1639135880.git.johannes.thumshirn@wdc.com/

b4 am 8a54e85cf93d2042f1a2e29517f8f91fce56f6ab.1639135880.git.johannes.thumshirn@wdc.com

**Comment by kdave** [comment]
Folded to the patch that caused it ("btrfs: zoned: cache reported zone during mount").
