### ISSUE TITLE
[PATCH] btrfs: fix missing log mutex unlock after failure to log

### ISSUE THREAD

**Issue by fdmanana** [btrfs/linux#414]
Link to patches

https://lore.kernel.org/linux-btrfs/b98e09dd2c88d71e92ebcfd083dc5687d53b9006.1644244472.git.fdmanana@suse.com/

b4 am b98e09dd2c88d71e92ebcfd083dc5687d53b9006.1644244472.git.fdmanana@suse.com

**Comment by kdave** [comment]
Folded to the patch.
