### ISSUE TITLE
[PATCH v2 0/2] fs: allow cross-vfsmount reflink/dedupe

### ISSUE THREAD

**Issue by josefbacik** [btrfs/linux#427]
Link to patches

https://lore.kernel.org/linux-btrfs/ef6f142a8be5bb8a3d2ac2643cc01870038f11b9.1645041975.git.josef@toxicpanda.com/

b4 am ef6f142a8be5bb8a3d2ac2643cc01870038f11b9.1645041975.git.josef@toxicpanda.com

**Comment by josefbacik** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1645194730.git.josef@toxicpanda.com/

b4 am cover.1645194730.git.josef@toxicpanda.com

**Comment by Atemu** [comment]
Is it safe to apply this to older kernels such as 5.15?
