### ISSUE TITLE
[PATCH] btrfs: avoid full commit due to race when logging dentry

### ISSUE THREAD

**Issue by fdmanana** [btrfs/linux#444]
Link to patches

https://lore.kernel.org/linux-btrfs/78d0dffe5f48910e126886559d0c69194b32eab9.1646416779.git.fdmanana@suse.com/

b4 am 78d0dffe5f48910e126886559d0c69194b32eab9.1646416779.git.fdmanana@suse.com

**Comment by kdave** [comment]
Folded.
