### ISSUE TITLE
[PATCH] btrfs: don't trigger autodefrag if cleaner is woken up early

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#450]
Link to patches

https://lore.kernel.org/linux-btrfs/d1ce90f37777987732b8ccf0edbfc961cd5c8873.1646912061.git.wqu@suse.com/

b4 am d1ce90f37777987732b8ccf0edbfc961cd5c8873.1646912061.git.wqu@suse.com

**Comment by kdave** [comment]
If this patch is still relevant, please resend (and without the TODO note).
