### ISSUE TITLE
[PATCH v2] btrfs: zoned: use alloc_list instead of RCU locked

### ISSUE THREAD

**Issue by morbidrsa** [btrfs/linux#454]
Link to patches

https://lore.kernel.org/linux-btrfs/f7108349f3a7d690166c88691c5dc1932cab3610.1647267391.git.johannes.thumshirn@wdc.com/

b4 am f7108349f3a7d690166c88691c5dc1932cab3610.1647267391.git.johannes.thumshirn@wdc.com

**Comment by kdave** [comment]
I've merged this one with the patch "btrfs: zoned: use alloc_list instead of RCU locked device_list" so we don't switch RCU and mutex back and forth.
