### ISSUE TITLE
[PATCH] btrfs: add a warning to check on the leaking device close

### ISSUE THREAD

**Issue by asj** [btrfs/linux#46]
Link to patches

https://lore.kernel.org/linux-btrfs/8ad72827dc32542915f87db73cbb6b609f24dce4.1600074377.git.anand.jain@oracle.com/

b4 am 8ad72827dc32542915f87db73cbb6b609f24dce4.1600074377.git.anand.jain@oracle.com

**Comment by kdave** [comment]
There have been patches touching device locking, please resend if this is still relevant.
