### ISSUE TITLE
[PATCH] btrfs: fix the uninitialized btrfs_bio::iter

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#460]
Link to patches

https://lore.kernel.org/linux-btrfs/f7698bebfcbd1687dbf8742290cd8d88b891590f.1647476483.git.wqu@suse.com/

b4 am f7698bebfcbd1687dbf8742290cd8d88b891590f.1647476483.git.wqu@suse.com

**Comment by kdave** [comment]
Patch updated.
