### ISSUE TITLE
[PATCH RFC] btrfs: verify the endio function at layer boundary

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#463]
Link to patches

https://lore.kernel.org/linux-btrfs/27688f5ed1d59b26255f285843c4573322acfa39.1647926689.git.wqu@suse.com/

b4 am 27688f5ed1d59b26255f285843c4573322acfa39.1647926689.git.wqu@suse.com

**Comment by kdave** [comment]
Discarded on request.
