### ISSUE TITLE
[PATCH] btrfs: restore inode creation before xattr setting

### ISSUE THREAD

**Issue by sweettea** [btrfs/linux#475]
Link to patches

https://lore.kernel.org/linux-btrfs/8a60e54c02d8951cf5650cc8452ae583c130bbf7.1649437335.git.sweettea-kernel@dorminy.me/

b4 am 8a60e54c02d8951cf5650cc8452ae583c130bbf7.1649437335.git.sweettea-kernel@dorminy.me

**Comment by kdave** [comment]
Folded to the patch.
