### ISSUE TITLE
[PATCH DRAFT] btrfs: RAID56J journal on-disk format draft

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#502]
Link to patches

https://lore.kernel.org/linux-btrfs/f6679e0b681f9b1a74dfccbe05dcb5b6eb0878f6.1653372729.git.wqu@suse.com/

b4 am f6679e0b681f9b1a74dfccbe05dcb5b6eb0878f6.1653372729.git.wqu@suse.com

**Comment by kdave** [comment]
We don't want to do journaling, next attempt is the write intent bitmap.
