### ISSUE TITLE
[PATCH 0/3] btrfs: fix a couple sleeps while holding a spinlock

### ISSUE THREAD

**Issue by fdmanana** [btrfs/linux#540]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1657097693.git.fdmanana@suse.com/

b4 am cover.1657097693.git.fdmanana@suse.com

**Comment by kdave** [comment]
Closing, it needs to be reworked so the locking is done before radix tree -> xarray switch. No target merge set, this is nice-to-have only.
