### ISSUE TITLE
[PATCH] btrfs: enhance unsupported compat RO flags handling

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#543]
Link to patches

https://lore.kernel.org/linux-btrfs/812f9641163f0b3340474acc83d096ff2bc2bab7.1657505260.git.wqu@suse.com/

b4 am 812f9641163f0b3340474acc83d096ff2bc2bab7.1657505260.git.wqu@suse.com

**Comment by kdave** [comment]
This will be merged within the block-group-tree patchset.
