### ISSUE TITLE
[PATCH v4] btrfs: skip update of block group item if used bytes are

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#545]
Link to patches

https://lore.kernel.org/linux-btrfs/64e4434370badd801a79a782613c405830475dde.1657521468.git.wqu@suse.com/

b4 am 64e4434370badd801a79a782613c405830475dde.1657521468.git.wqu@suse.com

**Comment by adam900710** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/bf157be545a0ad97897b33be983284a4f63a5e0f.1662618779.git.wqu@suse.com/

b4 am bf157be545a0ad97897b33be983284a4f63a5e0f.1662618779.git.wqu@suse.com

**Comment by adam900710** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/2a76b8005eb7208eda97e62a944ae456cbe8386f.1662705863.git.wqu@suse.com/

b4 am 2a76b8005eb7208eda97e62a944ae456cbe8386f.1662705863.git.wqu@suse.com

**Comment by adam900710** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/f68664759229da440226ebc28114108470b761b6.1663241717.git.wqu@suse.com/

b4 am f68664759229da440226ebc28114108470b761b6.1663241717.git.wqu@suse.com

**Comment by kdave** [comment]
Adding this back to 6.2.
