### ISSUE TITLE
[PATCH v5 00/18] btrfs: add fscrypt integration

### ISSUE THREAD

**Issue by sweettea** [btrfs/linux#549]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1657707686.git.sweettea-kernel@dorminy.me/

b4 am cover.1657707686.git.sweettea-kernel@dorminy.me

**Comment by sweettea** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1658623319.git.sweettea-kernel@dorminy.me/

b4 am cover.1658623319.git.sweettea-kernel@dorminy.me

**Comment by sweettea** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1660744500.git.sweettea-kernel@dorminy.me/

b4 am cover.1660744500.git.sweettea-kernel@dorminy.me

**Comment by sweettea** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1662420176.git.sweettea-kernel@dorminy.me/

b4 am cover.1662420176.git.sweettea-kernel@dorminy.me

**Comment by sweettea** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1666281276.git.sweettea-kernel@dorminy.me/

b4 am cover.1666281276.git.sweettea-kernel@dorminy.me

**Comment by sweettea** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1666651724.git.sweettea-kernel@dorminy.me/

b4 am cover.1666651724.git.sweettea-kernel@dorminy.me

**Comment by sweettea** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1667389115.git.sweettea-kernel@dorminy.me/

b4 am cover.1667389115.git.sweettea-kernel@dorminy.me

**Comment by kdave** [comment]
Preparatory work has been merged. Fscrypt changes needed to be merged befor the btrfs part.
