### ISSUE TITLE
[PATCH] btrfs: free device without BTRFS_MAGIC

### ISSUE THREAD

**Issue by asj** [btrfs/linux#57]
Link to patches

https://lore.kernel.org/linux-btrfs/dbc067b24194241f6d87b8f9799d9b6484984a13.1600473987.git.anand.jain@oracle.com/

b4 am dbc067b24194241f6d87b8f9799d9b6484984a13.1600473987.git.anand.jain@oracle.com

**Comment by josefbacik** [comment]
This has been superseded by #60
