### ISSUE TITLE
consolidate btrfs checksumming, repair and bio splitting v4

### ISSUE THREAD

**Issue by morbidrsa** [btrfs/linux#586]
Link to patches

https://lore.kernel.org/linux-btrfs/20220901074216.1849941-1-hch@lst.de/

b4 am 20220901074216.1849941-1-hch@lst.de

**Comment by kdave** [comment]
V2 https://lore.kernel.org/linux-btrfs/20221120124734.18634-1-hch@lst.de

**Comment by morbidrsa** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/20230121065031.1139353-1-hch@lst.de

b4 am 20230121065031.1139353-1-hch@lst.de
