### ISSUE TITLE
[PATCH] btrfs: fix rw_devices count in __btrfs_free_extra_devids

### ISSUE THREAD

**Issue by asj** [btrfs/linux#61]
Link to patches

https://lore.kernel.org/linux-btrfs/b3a0a629df98bd044a1fd5c4964f381ff6e7aa05.1600777827.git.anand.jain@oracle.com/

b4 am b3a0a629df98bd044a1fd5c4964f381ff6e7aa05.1600777827.git.anand.jain@oracle.com

**Comment by kdave** [comment]
Superseded by #112
