### ISSUE TITLE
[PATCH 0/2] btrfs-progs: receive: address setattr failures

### ISSUE THREAD

**Issue by fdmanana** [btrfs/linux#639]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1667494221.git.fdmanana@suse.com/

b4 am cover.1667494221.git.fdmanana@suse.com

**Comment by kdave** [comment]
Now tracked in https://github.com/kdave/btrfs-progs/issues/538 as it's for btrfs-progs.
