### ISSUE TITLE
[PATCH v9 00/41] btrfs: zoned block device support (part 1)

### ISSUE THREAD

**Issue by morbidrsa** [btrfs/linux#64]
Link to patches

https://lore.kernel.org/linux-btrfs/20200911123259.3782926-1-naohiro.aota@wdc.com
b4 am 20200911123259.3782926-1-naohiro.aota@wdc.com

**Comment by naota** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1601572459.git.naohiro.aota@wdc.com/

b4 am cover.1601572459.git.naohiro.aota@wdc.com

**Comment by naota** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1604065156.git.naohiro.aota@wdc.com/

b4 am cover.1604065156.git.naohiro.aota@wdc.com

**Comment by naota** [comment]
BTW, btrfs-create-issue failed to update the title and remove the "update" label.

> {
>   "message": "Must have admin rights to Repository.",
>   "documentation_url": "https://docs.github.com/rest/reference/issues#update-an-issue"
> }
> gh: Must have admin rights to Repository. (HTTP 403)
> {
>   "message": "Must have admin rights to Repository.",
>   "documentation_url": "https://docs.github.com/rest/reference/issues#remove-a-label-from-an-issue"
> }
> gh: Must have admin rights to Repository. (HTTP 403)

**Comment by kdave** [comment]
https://lore.kernel.org/linux-btrfs/cover.1604065156.git.naohiro.aota@wdc.com/

b4 am cover.1604065156.git.naohiro.aota@wdc.com

**Comment by naota** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1605007036.git.naohiro.aota@wdc.com/

b4 am cover.1605007036.git.naohiro.aota@wdc.com
