### ISSUE TITLE
[PATCH] btrfs: fix improper error handling in btrfs_unlink

### ISSUE THREAD

**Issue by boryas** [btrfs/linux#640]
Link to patches

https://lore.kernel.org/linux-btrfs/d1213451ff43c39304d949881a2fa4e8a8b561b3.1667523745.git.boris@bur.io/

b4 am d1213451ff43c39304d949881a2fa4e8a8b561b3.1667523745.git.boris@bur.io

**Comment by kdave** [comment]
Folded to the patch.
