### ISSUE TITLE
[PATCH] btrfs: make btrfs_get_io_geometry() to return void

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#666]
Link to patches

https://lore.kernel.org/linux-btrfs/b3d2350ae3920a475a43dba6f979731420859dc8.1670390031.git.wqu@suse.com/

b4 am b3d2350ae3920a475a43dba6f979731420859dc8.1670390031.git.wqu@suse.com

**Comment by kdave** [comment]
Superseded by #586
