### ISSUE TITLE
[PATCH v7 00/13] btrfs: introduce RAID stripe tree

### ISSUE THREAD

**Issue by morbidrsa** [btrfs/linux#667]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1670422590.git.johannes.thumshirn@wdc.com/

b4 am cover.1670422590.git.johannes.thumshirn@wdc.com

**Comment by morbidrsa** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1675853489.git.johannes.thumshirn@wdc.com/

b4 am cover.1675853489.git.johannes.thumshirn@wdc.com

**Comment by morbidrsa** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1676470614.git.johannes.thumshirn@wdc.com/

b4 am cover.1676470614.git.johannes.thumshirn@wdc.com

**Comment by morbidrsa** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1677750131.git.johannes.thumshirn@wdc.com/

b4 am cover.1677750131.git.johannes.thumshirn@wdc.com

**Comment by kdave** [comment]
Moving to backlog project

**Comment by morbidrsa** [comment]
Superseded by #944
