### ISSUE TITLE
[PATCH] btrfs-progs: fix return code for failed replace start

### ISSUE THREAD

**Issue by asj** [btrfs/linux#67]
Link to patches

https://lore.kernel.org/linux-btrfs/48194115537d723d04bba0505411525b77f3e73b.1601402292.git.anand.jain@oracle.com/

b4 am 48194115537d723d04bba0505411525b77f3e73b.1601402292.git.anand.jain@oracle.com

**Comment by kdave** [comment]
This is patch for progs, the issues are supposed to track only kernel patches.
