### ISSUE TITLE
[PATCH] btrfs: new test for logical inode resolution panic

### ISSUE THREAD

**Issue by boryas** [btrfs/linux#677]
Link to patches

https://lore.kernel.org/linux-btrfs/98d2055515cd765b0835a7f751a21cbb72c03621.1671059406.git.boris@bur.io/

b4 am 98d2055515cd765b0835a7f751a21cbb72c03621.1671059406.git.boris@bur.io

**Comment by kdave** [comment]
No fstests patches here please, I'll delete the issue.
