### ISSUE TITLE
[PATCH] btrfs: don't clear EXTENT_BUFFER_DIRTY bit if the tree block

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#681]
Link to patches

https://lore.kernel.org/linux-btrfs/ed62dbe7094fb5e80cb5b6df8590ff621b218ae5.1671252987.git.wqu@suse.com/

b4 am ed62dbe7094fb5e80cb5b6df8590ff621b218ae5.1671252987.git.wqu@suse.com

**Comment by kdave** [comment]
Depends on #670 that will be reworked.
