### ISSUE TITLE
[PATCH v2] btrfs: scrub: avoid unnecessary extent tree search for simple

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#689]
Link to patches

https://lore.kernel.org/linux-btrfs/e8b3a59de5f43c185427a8d87c303ba3e8ff6ff1.1673244671.git.wqu@suse.com/

b4 am e8b3a59de5f43c185427a8d87c303ba3e8ff6ff1.1673244671.git.wqu@suse.com

**Comment by adam900710** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/8d8e77d19cb56fc954353a659b5382ecf0c4a0d6.1677723997.git.wqu@suse.com/

b4 am 8d8e77d19cb56fc954353a659b5382ecf0c4a0d6.1677723997.git.wqu@suse.com

**Comment by kdave** [comment]
Moving to backlog.

**Comment by kdave** [comment]
Closing.
