### ISSUE TITLE
[PATCH] btrfs: keep sysfs features in tandem with runtime features

### ISSUE THREAD

**Issue by asj** [btrfs/linux#694]
Link to patches

https://lore.kernel.org/linux-btrfs/ef0efdacd9bd53a55a02c6419b9ff0d51edf5408.1673412612.git.anand.jain@oracle.com/

b4 am ef0efdacd9bd53a55a02c6419b9ff0d51edf5408.1673412612.git.anand.jain@oracle.com

**Comment by kdave** [comment]
Superseded by #698
