### ISSUE TITLE
[PATCH] btrfs: separate single stripe optimization into a dedicate

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#709]
Link to patches

https://lore.kernel.org/linux-btrfs/4e4d6e0aab34ab40fd0ac69874141bb02a559f10.1674546545.git.wqu@suse.com/

b4 am 4e4d6e0aab34ab40fd0ac69874141bb02a559f10.1674546545.git.wqu@suse.com

**Comment by kdave** [comment]
Per comments will be reworked or redone in another series.
