### ISSUE TITLE
[PATCH v2] btrfs: fix size class loading logic

### ISSUE THREAD

**Issue by boryas** [btrfs/linux#710]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1674679476.git.boris@bur.io/

b4 am cover.1674679476.git.boris@bur.io

**Comment by boryas** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/1c4c25be5fa66e14ae772f134045f64cf1fb74a6.1674686119.git.boris@bur.io/

b4 am 1c4c25be5fa66e14ae772f134045f64cf1fb74a6.1674686119.git.boris@bur.io

**Comment by kdave** [comment]
Folded.
