### ISSUE TITLE
[PATCH v2] btrfs: make btrfs_bin_search a macro

### ISSUE THREAD

**Issue by asj** [btrfs/linux#729]
Link to patches

https://lore.kernel.org/linux-btrfs/520705d35cbfb6c21d1e89481f8a4d0343daa138.1676986303.git.anand.jain@oracle.com/

b4 am 520705d35cbfb6c21d1e89481f8a4d0343daa138.1676986303.git.anand.jain@oracle.com

**Comment by asj** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/8b986d23bf05684ae37102993b406e4e582dec39.1676991868.git.anand.jain@oracle.com/

b4 am 8b986d23bf05684ae37102993b406e4e582dec39.1676991868.git.anand.jain@oracle.com

**Comment by kdave** [comment]
Rework as suggeste.d
