### ISSUE TITLE
[PATCH] btrfs: scrub: fix an error in stripe offset calculation

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#731]
Link to patches

https://lore.kernel.org/linux-btrfs/c8f91363ab2e7ca24edbddf1feeca6c9fcf34f6e.1677033010.git.wqu@suse.com/

b4 am c8f91363ab2e7ca24edbddf1feeca6c9fcf34f6e.1677033010.git.wqu@suse.com

**Comment by kdave** [comment]
Folded.
