### ISSUE TITLE
[PATCH] btrfs: fix the mount crash caused by confusing return value

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#734]
Link to patches

https://lore.kernel.org/linux-btrfs/2de92bdcebd36e4119467797dedae8a9d97a9df3.1677314616.git.wqu@suse.com/

b4 am 2de92bdcebd36e4119467797dedae8a9d97a9df3.1677314616.git.wqu@suse.com

**Comment by kdave** [comment]
Resend as cleanup.
