### ISSUE TITLE
[PATCH] btrfs: refactor __btrfs_map_block()

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#735]
Link to patches

https://lore.kernel.org/linux-btrfs/e7d711b6ea444e2f018516f4187f9a614e81af38.1677394468.git.wqu@suse.com/

b4 am e7d711b6ea444e2f018516f4187f9a614e81af38.1677394468.git.wqu@suse.com

**Comment by kdave** [comment]
I'm not sure how much this still applies,  there were a lot of changes to the bbio code. Please resend if neded and does not interfere with other upcoming changes in that area.
