### ISSUE TITLE
[RFC PATCH] btrfs: remove struct scrub_stx for superblock scrubbing

### ISSUE THREAD

**Issue by asj** [btrfs/linux#752]
Link to patches

https://lore.kernel.org/linux-btrfs/10d0f55b196d4dc949f0ac29f2f0af023eaa7523.1679376183.git.anand.jain@oracle.com/

b4 am 10d0f55b196d4dc949f0ac29f2f0af023eaa7523.1679376183.git.anand.jain@oracle.com

**Comment by kdave** [comment]
Will be folded to the scrub rework series.
