### ISSUE TITLE
[PATCH v11 00/14] btrfs: add ioctls and send/receive support for reading/writing compressed data

### ISSUE THREAD

**Issue by kdave** [btrfs/linux#76]
https://lore.kernel.org/linux-btrfs/cover.1597994106.git.osandov@osandov.com/

b4 am cover.1597994106.git.osandov@osandov.com

**Comment by osandov** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1605723600.git.osandov@fb.com/

b4 am cover.1605723600.git.osandov@fb.com

**Comment by osandov** [comment]
https://lore.kernel.org/linux-btrfs/<cover.1630514529.git.osandov@fb.com>/

b4 am <cover.1630514529.git.osandov@fb.com>
