### ISSUE TITLE
[PATCH RFC] btrfs: make dev-scrub as an exclusive operation

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#782]
Link to patches

https://lore.kernel.org/linux-btrfs/ef0c22ce3cf2f7941634ed1cb2ca718f04ce675d.1682296794.git.wqu@suse.com/

b4 am ef0c22ce3cf2f7941634ed1cb2ca718f04ce675d.1682296794.git.wqu@suse.com

**Comment by kdave** [comment]
Seems that we don't need scrub to be exclusive op, closing.
