### ISSUE TITLE
[PATCH] btrfs: always assign false literal to ref head processing

### ISSUE THREAD

**Issue by fdmanana** [btrfs/linux#823]
Link to patches

https://lore.kernel.org/linux-btrfs/0a50236c4f79f588c48f44dfd80519423bbacb1c.1686298104.git.fdmanana@suse.com/

b4 am 0a50236c4f79f588c48f44dfd80519423bbacb1c.1686298104.git.fdmanana@suse.com

**Comment by kdave** [comment]
Folded to the patch.
