### ISSUE TITLE
[PATCH v2 00/17] btrfs: add encryption feature

### ISSUE THREAD

**Issue by sweettea** [btrfs/linux#852]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1687988380.git.sweettea-kernel@dorminy.me/

b4 am cover.1687988380.git.sweettea-kernel@dorminy.me

**Comment by sweettea** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1689564024.git.sweettea-kernel@dorminy.me/

b4 am cover.1689564024.git.sweettea-kernel@dorminy.me

**Comment by kdave** [comment]
Superseded by #901
