### ISSUE TITLE
[PATCH] btrfs: speedup scrub csum verification

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#858]
Link to patches

https://lore.kernel.org/linux-btrfs/6c1ffe48e93fee9aa975ecc22dc2e7a1f3d7a0de.1688539673.git.wqu@suse.com/

b4 am 6c1ffe48e93fee9aa975ecc22dc2e7a1f3d7a0de.1688539673.git.wqu@suse.com

**Comment by kdave** [comment]
Will be reworked.
