### ISSUE TITLE
[PATCH 0/3] btrfs: make extent buffer memory continuous

### ISSUE THREAD

**Issue by adam900710** [btrfs/linux#883]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1690249862.git.wqu@suse.com/

b4 am cover.1690249862.git.wqu@suse.com

**Comment by kdave** [comment]
Moving to backlog projects. We need the contig pages but not the vmap/vm_map approach, there are some ways how to do it so this needs to be benchmarked. Also the fallback to page-by-page is likely to stay.

**Comment by adam900710** [comment]
OK, I guess I will just go the co-exist path for now (meaning will have a variable telling if we need the cross-page handling).

This would lead to extra branches thus worse performance, but I hope this won't bring obvious performance drop, so that I can continue my work on the folio convert.
