### ISSUE TITLE
[PATCH v10 0/3] readmirror feature (read_policy sysfs and in-memory only approach)

### ISSUE THREAD

**Issue by asj** [btrfs/linux#91]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1602756068.git.anand.jain@oracle.com/

b4 am cover.1602756068.git.anand.jain@oracle.com

**Comment by kdave** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1603347462.git.anand.jain@oracle.com/

b4 am cover.1603347462.git.anand.jain@oracle.com
