### ISSUE TITLE
[PATCH] btrfs: qgroup: fix double unlock in btrfs_quota_disable

### ISSUE THREAD

**Issue by boryas** [btrfs/linux#990]
Link to patches

https://lore.kernel.org/linux-btrfs/1ed61ba7891b9f86a20a46ee5bb42cb4649311af.1695833099.git.boris@bur.io/

b4 am 1ed61ba7891b9f86a20a46ee5bb42cb4649311af.1695833099.git.boris@bur.io

**Comment by kdave** [comment]
Folded to the commit.
