### ISSUE TITLE
[PATCH] btrfs: perform stripe tree lookup for scrub

### ISSUE THREAD

**Issue by morbidrsa** [btrfs/linux#999]
Link to patches

https://lore.kernel.org/linux-btrfs/4895772fd73872ee2cc23d152e50db28a5ca5bbc.1696867165.git.johannes.thumshirn@wdc.com/

b4 am 4895772fd73872ee2cc23d152e50db28a5ca5bbc.1696867165.git.johannes.thumshirn@wdc.com

**Comment by kdave** [comment]
Folded to the patch.
